import './globals.css'
import NavigationBar from '@/components/core/navigation-bar'
import Footer from '@/components/core/footer'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <header><NavigationBar></NavigationBar></header>
      <body>{children}</body>
      <footer><Footer></Footer></footer>
    </html>
  )
}
