import './globals.css'
import NavigationBar from '@/components/ui/navigation-bar'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <header><NavigationBar></NavigationBar></header>
      <body>{children}</body>
    </html>
  )
}
